### ISSUE TITLE
QPSU dependencies : pip conda

### ISSUE THREAD

**Issue by QGB** [QGB/QPSU#6]
pip install --user dill flask tld qqwry-py3 wdom astor pymysql progressbar2 pympler jieba fake_headers sqlalchemy  flask-sqlalchemy requests bs4 redis pypinyin  elasticsearch==6.4 elasticsearch-dsl==6.3 pyahocorasick 

!/root/anaconda3/bin/conda config --add channels conda-forge
!/root/anaconda3/bin/conda install pyahocorasick
!/root/anaconda3/bin/conda install elasticsearch=6.3 elasticsearch-dsl=6.3

**Comment by QGB** [comment]
conda install xlwings numpy=1.13

**Comment by QGB** [comment]
python -m pip install -i http://pypi.douban.com/simple --trusted-host pypi.douban.com dill flask tld qqwry-py3 wdom astor pymysql progressbar2 pympler jieba fake_headers sqlalchemy flask-sqlalchemy requests bs4 redis pypinyin elasticsearch==6.4 elasticsearch-dsl==6.3 aiohttp aiodns pywinauto ipython dulwich

**Comment by QGB** [comment]
Termux  python does not   installed  chardet

**Comment by QGB** [comment]
F.write_xls()  F.write_xlsx()
```
pip install  -i http://pypi.douban.com/simple --trusted-host pypi.douban.com xlwt openpyxl 

```

**Comment by QGB** [comment]
apt install python3-pip python3-ipython

**Comment by QGB** [comment]
python -m pip install --upgrade pip

**Comment by QGB** [comment]
```
In [690]: pip install giturlparse
Collecting giturlparse
##qgb## C:\Users\qgb\AppData\Local\Temp\pip-unpack-7cq9h30z\giturlparse-0.10.0-py2.py3-none-any.whl application/octet-stream <pip._internal.utils.hashes.Hashes object at 0x0000029AB1BB6EC8> on <Response [200]> https://files.pythonhosted.org/packages/a2/01/baa326ad32510acd3f08835e1b9f3c66170ddf7dfcc233640ff22d0ea619/giturlparse-0.10.0-py2.py3-none-any.whl#sha256=04ba1a3a099c3093fa8d24a422913c6a9b2c2cd22bcffc939cf72e3e98f672d7 (from https://pypi.org/simple/giturlparse/) (requires-python:>=3.6)
  Downloading https://files.pythonhosted.org/packages/a2/01/baa326ad32510acd3f08835e1b9f3c66170ddf7dfcc233640ff22d0ea619/giturlparse-0.10.0-py2.py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-req-tracker-dphrbllh\\f436e0dccc6b34e578c560fccd5b175befadb408289acdd406bdf8b6'

Note: you may need to restart the kernel to use updated packages.

In [691]: pip install --ignore-installed pip
Collecting pip
##qgb## C:\Users\qgb\AppData\Local\Temp\pip-unpack-jv5w09q8\pip-21.1.2-py3-none-any.whl application/octet-stream <pip._internal.utils.hashes.Hashes object at 0x00000174ADA88808> on <Response [200]> https://files.pythonhosted.org/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl#sha256=f8ea1baa693b61c8ad1c1d8715e59ab2b93cd3c4769bacab84afcc4279e7a70e (from https://pypi.org/simple/pip/) (requires-python:>=3.6)
  Downloading https://files.pythonhosted.org/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.6MB 11kB/s
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-req-tracker-dphrbllh\\3955c962c790b5ee4b863a4c609717abd0f11430406be61920a1e360'

Note: you may need to restart the kernel to use updated packages.

In [692]: conda search pip
Loading channels: \                                                                                           




    if not ext and link.url != resp.url:
        ext = os.path.splitext(resp.url)[1]
        if ext:
            filename += ext
    file_path = os.path.join(temp_dir, filename)
    print('##qgb##',file_path,content_type, hashes, progress_bar,resp, link,)
    if 'mxnet-1.6' in file_path:
        if not input(file_path+'Enter to skip ,or any char to continue.. :'):
            return file_path, content_type
    with open(file_path, 'wb') as content_file:
        _download_url(resp, link, content_file, hashes, progress_bar)
    return file_path, content_type

```
![image](https://user-images.githubusercontent.com/8005654/121578308-1ea79300-ca5d-11eb-9380-69597ac5d8bb.png)

**Comment by QGB** [comment]
`conda install pip`
自动安装最新版 pip，覆盖老版pip. 
ipython不重启pip还是有问题，重启进程 `ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\qgb\\AppData\\Local\\Temp\\pip-req-tracker-dphrbllh\\3955c962c790b5ee4b863a4c609717abd0f11430406be61920a1e360'
` 问题解决

**Comment by QGB** [comment]
```
In [174]: pip install youtube_dl
Traceback (most recent call last):
  File "C:\QGB\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\QGB\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\QGB\Anaconda3\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\QGB\Anaconda3\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\QGB\Anaconda3\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\QGB\Anaconda3\lib\site-packages\pip\_internal\cli\main_parser.py", line 10, in <module>
    from pip._internal.commands import commands_dict, get_similar_commands
  File "C:\QGB\Anaconda3\lib\site-packages\pip\_internal\commands\__init__.py", line 9, in <module>
    from pip._internal.cli.base_command import Command
  File "C:\QGB\Anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 36, in <module>
    from pip._internal.utils.typing import MYPY_CHECK_RUNNING
ModuleNotFoundError: No module named 'pip._internal.utils.typing'
Note: you may need to restart the kernel to use updated packages.

In [175]: conda install --force-reinstall pip==20.0.2


The following packages will be UPDATED:

  conda                               4.10.1-py37h03978a9_0 --> 4.10.3-py37h03978a9_0

The following packages will be SUPERSEDED by a higher-priority channel:

  pip                conda-forge/noarch::pip-21.1.2-pyhd8e~ --> conda-forge/win-64::pip-20.0.2-py37_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-20.0.2           | 1.9 MB    | ############################################################################ | 100%
conda-4.10.3         | 3.1 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by QGB** [comment]
```
pip install dulwich paramiko  

from qgb import py,U,T,N,F,git
```

**Comment by QGB** [comment]
https://repo.anaconda.com/pkgs/main/noarch/current_repodata.json

 1.054 MiB{\n  "info": {\n    "subdir": "noarch"\n  },\n  "packages": {\n    "_sysroot_linux

```
In [5]: conda install pycryptodomex
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/noarch'



Note: you may need to restart the kernel to use updated packages.
```

**Comment by QGB** [comment]
```


g++:
arm-linux-gnueabihf-gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory


!apt install -y tmux python3.8-distutils cifs-utils python3.8-dev gcc g++

```
