### ISSUE TITLE
U

### ISSUE THREAD

**Issue by QGB** [QGB/QPSU#7]
U.input  is3  RecursionError: maximum recursion depth exceeded in comparison

**Comment by QGB** [comment]
RustPython
>>>>> from qgb import U
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_frozen_importlib", line 1113, in __import__
  File "_frozen_importlib", line 1050, in _handle_fromlist
  File "_frozen_importlib", line 1042, in _handle_fromlist
  File "_frozen_importlib", line 1014, in _gcd_import
  File "_frozen_importlib", line 991, in _find_and_load
  File "_frozen_importlib", line 975, in _find_and_load_unlocked
  File "_frozen_importlib", line 686, in _load_unlocked
  File "_frozen_importlib", line 684, in _load_unlocked
  File "_frozen_importlib", line 677, in _load_unlocked
  File "_frozen_importlib", line 671, in _load_unlocked
  File "_frozen_importlib_external", line 788, in exec_module
  File "/home/qgb/qgb/U.py", line 8, in <module>
    stdin=sys.stdin;stdout=sys.stdout;stderr=sys.stderr
AttributeError: module 'sys' has no attribute 'stdin'
https://github.com/RustPython/RustPython/pull/1514

sys.stdin = sys.__stdin__ = getattr(sys, '__stdin__', False) or os.fdopen(0, "r")
sys.stdout = sys.__stdin__ = getattr(sys, '__stdout__', False) or os.fdopen(1, "w")
sys.stderr = sys.__stdin__ = getattr(sys, '__stderr__', False) or os.fdopen(2, "w")

**Comment by QGB** [comment]
dict_add_value_list
