### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by QGB** [QGB/QPSU#9]
C:\Users\qgb\Documents>C:\QGB\Anaconda3\python.exe -c "import sys,os;sys.path.append(r'C:\QGB\babun/cygwin/bin');from qgb import *;U.cb.set(r''' site:zhihu.com ''')"
#Error py lib import inconsistent use of tabs and spaces in indentation (selectors.py, line 314)
#Error py lib import inconsistent use of tabs and spaces in indentation (selectors.py, line 314)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\QGB\babun/cygwin/bin\qgb\U.py", line 219, in <module>
    if iswin() or iscyg():
  File "C:\QGB\babun/cygwin/bin\qgb\U.py", line 179, in isWin
    if platform.system().startswith('Windows'):return True
  File "C:\QGB\Anaconda3\lib\platform.py", line 1068, in system
    return uname().system
  File "C:\QGB\Anaconda3\lib\platform.py", line 956, in uname
    node = _node()
  File "C:\QGB\Anaconda3\lib\platform.py", line 759, in _node
    import socket
  File "C:\QGB\Anaconda3\lib\socket.py", line 52, in <module>
    import os, sys, io, selectors
  File "C:\QGB\Anaconda3\lib\selectors.py", line 314
    r, w, x = select.select(r, w, w, timeout)
                                            ^
TabError: inconsistent use of tabs and spaces in indentation
C:\Users\qgb\Documents>

**Comment by QGB** [comment]
```
/r=U.sys_actions([['click',(None,None)],['click',(None,None)],['click',(None,None)]],delay=0.4999) #地址栏不选中

中间的值 有时会选中

/r=U.sys_actions([['click',(None,None)],['click',(None,None)],['click',(None,None)]],delay=0.499) #地址栏选中
```

**Comment by QGB** [comment]
open file extension process as administrator

```
Windows Registry Editor Version 5.00

;pptx
[HKEY_CLASSES_ROOT\PowerPoint.Show.12\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\POWERPNT.EXE\" \"%1\""

;ppt
[HKEY_CLASSES_ROOT\PowerPoint.Show.8\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\POWERPNT.EXE\" \"%1\""

;.ppsx  PowerPoint.SlideShow.12

;docx
[HKEY_CLASSES_ROOT\Word.Document.12\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\WINWORD.EXE\" \"%1\""

;doc
[HKEY_CLASSES_ROOT\Word.Document.8\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\WINWORD.EXE\" \"%1\""


;xlsx
[HKEY_CLASSES_ROOT\Excel.Sheet.12\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\EXCEL.EXE\" \"%1\""

;xls
[HKEY_CLASSES_ROOT\Excel.Sheet.8\shell\runas\command]
@="\"C:\\QGB\\software\\Office2007\\EXCEL.EXE\" \"%1\""



```

**Comment by QGB** [comment]
```
ipdb> !open(file[:221],'a',encoding="utf8")
<_io.TextIOWrapper name="ipy/U.set_env_path(append=r'''＼＼192.168.1.3＼c＼QGB＼Anaconda3 ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼mingw-w64＼bin ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼usr＼bin ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼bin ＼＼192.168.1.3＼c＼QGB＼A" mode='a' encoding='utf8'>
ipdb> !open(file[:222],'a',encoding="utf8")
*** FileNotFoundError: [Errno 2] No such file or directory: "ipy/U.set_env_path(append=r'''＼＼192.168.1.3＼c＼QGB＼Anaconda3 ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼mingw-w64＼bin ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼usr＼bin ＼＼192.168.1.3＼c＼QGB＼Anaconda3＼Library＼bin ＼＼192.168.1.3＼c＼QGB＼An"
ipdb>
```

**Comment by QGB** [comment]
```

PageError: net::ERR_CONNECTION_FAILED at https://oshwhub.com/sign_in
In [21]:

Traceback (most recent call last):
  File "c:\QGB\Anaconda3\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
             ^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\site-packages\IPython\__init__.py", line 130, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "c:\QGB\Anaconda3\Lib\site-packages\IPython\terminal\ipapp.py", line 317, in start
    self.shell.mainloop()
  File "c:\QGB\Anaconda3\Lib\site-packages\IPython\terminal\interactiveshell.py", line 911, in mainloop
    self.interact()
  File "c:\QGB\Anaconda3\Lib\site-packages\IPython\terminal\interactiveshell.py", line 896, in interact
    code = self.prompt_for_code()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\site-packages\IPython\terminal\interactiveshell.py", line 839, in prompt_for_code
    text = self.pt_app.prompt(
           ^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 1026, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\site-packages\prompt_toolkit\application\application.py", line 1002, in run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\asyncio\runners.py", line 189, in run
    with Runner(debug=debug) as runner:
  File "c:\QGB\Anaconda3\Lib\asyncio\runners.py", line 59, in __enter__
    self._lazy_init()
  File "c:\QGB\Anaconda3\Lib\asyncio\runners.py", line 137, in _lazy_init
    self._loop = events.new_event_loop()
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\asyncio\events.py", line 806, in new_event_loop
    return get_event_loop_policy().new_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\asyncio\events.py", line 695, in new_event_loop
    return self._loop_factory()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\asyncio\windows_events.py", line 315, in __init__
    super().__init__(proactor)
  File "c:\QGB\Anaconda3\Lib\asyncio\proactor_events.py", line 639, in __init__
    self._make_self_pipe()
  File "c:\QGB\Anaconda3\Lib\asyncio\proactor_events.py", line 784, in _make_self_pipe
    self._ssock, self._csock = socket.socketpair()
                               ^^^^^^^^^^^^^^^^^^^
  File "c:\QGB\Anaconda3\Lib\socket.py", line 641, in socketpair
    csock.connect((addr, port))
OSError: [WinError 10055] 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。


```
